CC = icc
#CC = gcc
#CC = clang
FC = ifort
#FC = gfortran
AR = ar
PLATFORM = # -D__DARWIN
INCLUDE = -I${CURDIR}/src
PTHREAD_CFLAG = -pthread
PTHREAD_FFLAG = -reentrancy threaded
CFLAGS = $(PLATFORM) $(INCLUDE) -fPIC -Wimplicit-function-declaration $(PTHREAD_CFLAG)
FFLAGS = $(PLATFORM) $(INCLUDE) -cpp -fPIC -recursive -implicitnone $(PTHREAD_FFLAG)
LIB = 
OPTFLAGS = -Ofast
DEBUG = $(OPTFLAGS) -g # -rdynamic -backtrace -O0 -check all -debug all
#CDEBUG = $(DEBUG)  -I/usr/include/x86_64-linux-gnu/
CDEBUG = $(DEBUG)  
FDEBUG = $(DEBUG)
OUTPUT_DIR = ${CURDIR}/pthread_ifort
